// pages/index.tsx
import Head from "next/head";
import Header from "../components/Header";
import IntroSection from "../components/IntroSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Header />
          <IntroSection />
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* Add other sections here */}
        </div>
      </main>
    </>
  );
}
